<?php
/**
 * Email:zhaojunlike@gmail.com
 * Date: 7/8/2017
 * Time: 5:28 PM
 */

namespace app\index\controller;


use app\common\cache\AuthCache;
use app\common\core\Auth as ViewAuth;

class Auth extends Base
{

    protected $_rule = [];

    #region start


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_checkAuth();
    }

    private function _checkAuth()
    {
        $viewAuthChecker = ViewAuth::Instance();
        $rules = [$this->request->module(), $this->request->controller(), $this->request->action()];
        switch ($viewAuthChecker->checkAuth($rules, $this->mUser)) {
            case ViewAuth::$AUTH_CODES['success']:
                break;
            case ViewAuth::$AUTH_CODES['not_found']:
                $this->error("对不起,未知的请求权限访问");
                break;
            case ViewAuth::$AUTH_CODES['denial']:
                $this->error("对不起,权限拒绝访问");
                break;
            default:
                break;
        }
        $this->_rule = $viewAuthChecker->getRule();
        $this->assign('_rule', $this->_rule);
    }

    #endregion

    public function index()
    {

        return $this->fetch();
    }

    public function authRule()
    {
        if ($this->request->isPost()) {
            //json


        } else {
            $tree = AuthCache::getAuthRulesTree();
            $menus = $tree->DeepTree();
            $this->assign('data_list', $menus);
            return $this->fetch();
        }
    }

}