<?php
/**
 * Email:zhaojunlike@gmail.com
 * Date: 7/8/2017
 * Time: 5:28 PM
 */

namespace app\index\controller;


use app\common\cache\AuthCache;
use app\common\model\User;
use think\Session;
use app\common\core\Auth as ViewAuth;

class Auth extends Base
{
    #region start

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $token = Session::get("user_token");
        if (!$token) {
            //$this->error("请先登陆系统后操作", url("portal/login"));
            //使用游客权限登陆
//            $token = [
//                'id' => -1,
//                'username' => '游客',
//            ];
        } else {
            //更新一下
            $token = User::where(['id' => $token['id']])
                ->with('headPic')
                ->with('admin')
                ->find();
            Session::set('user_token', $token);
        }
        $this->mUser = $token;

        $tree = AuthCache::getAuthRulesTree(1, $this->request->module());
        $this->mAuthMenu = $tree->DeepTree();
        $this->assign('_menu', $this->mAuthMenu);


//        if (!isset($this->mUser['admin'])) {
//            $this->_checkAuth();
//        } else if ($this->mUser['admin']['is_root'] !== 1) {
//            $this->_checkAuth();
//        }

        $this->assign('_user', $this->mUser);
    }


    private function _checkLogin()
    {

    }

    private function _checkAuth()
    {
        $viewAuthChecker = ViewAuth::Instance();
        $rules = [$this->request->module(), $this->request->controller(), $this->request->action()];
        switch ($viewAuthChecker->checkAuth($rules, $this->mUser['id'])) {
            case ViewAuth::$AUTH_CODES['success']:
                break;
            case ViewAuth::$AUTH_CODES['not_found']:
                $this->error("对不起,未知的请求权限访问");
                break;
            case ViewAuth::$AUTH_CODES['denial']:
                $this->error("对不起,权限拒绝访问");
                break;
            default:
                break;
        }
    }

    #endregion

    public function index()
    {

        return $this->fetch();
    }

    public function authRule()
    {
        if ($this->request->isPost()) {
            //json


        } else {
            $tree = AuthCache::getAuthRulesTree();
            $menus = $tree->DeepTree();
            $this->assign('data_list', $menus);
            return $this->fetch();
        }
    }

}